services:
  - type: web
    name: stayzest-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    root: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://stayzest-cbf59.web.app
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
